version: '3.8'

volumes:
  mongodb_data_volume:
  postgres_data_volume:

services:

  rabbitmq:
    build: ./RabbitMQ
    ports:
      - 5672:5672
      - 15672:15672

  mongo_db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=processing_root_user
      - MONGO_INITDB_ROOT_PASSWORD=root_s3o1Ly590d23PkB0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_volume:/data/db

  postgres:
    build: ./PostgreSQL
    ports:
      - 5432:5432
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
      
  inference:
    build: ./inference

  app:
    build: .
    volumes:
      - ./AssrWeb:/AssrWeb

    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: bash -c "cd /AssrWeb && python manage.py makemigrations --settings=DjangoAssr.settings.dev_postgress && python manage.py migrate --settings=DjangoAssr.settings.dev_postgress && python manage.py runserver --settings=DjangoAssr.settings.dev_postgress 0.0.0.0:8000"

  nginx:
    build: ./nginx
    volumes:
      - ./AssrWeb/static:/static
    ports:
      - 80:80
