version: '3.8'
services:
  db:
    build: ./PostgreSQL
    ports:
      - 5432:5432
  app:
    build: .
    expose:
      - "8000"
    command: python manage.py runserver 0.0.0.0:8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - /home/bazoid/ASSR-deployment/ASSR/AssrWeb/static/:/static/