# Generated by Django 5.1.2 on 2024-10-12 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestingTagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestingMetadataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('author', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('creationData', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('keyValue', models.JSONField()),
                ('tag', models.ManyToManyField(to='MetaCommon.testingtagsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
