FROM huggingface/transformers-torch-light:latest
ENV PIP_NO_CACHE_DIR 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY / /code/

WORKDIR /code/
RUN pip3 install -r requirements39.txt
RUN python -c "import nltk; nltk.download('punkt_tab')"

WORKDIR /code/py_inference/
CMD ["celery", "-A", "main", "worker", "--loglevel=INFO"]
