name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: AssrWeb
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test
  build:
    needs:
      - tests
    runs-on: ubuntu-22.04
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: docker
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.docker_login}}
          password: ${{secrets.docker_pass}}
      - name: build-push-backend
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: shizvizor/app-assr:latest
      - name: build-push-nginx
        run: docker build -t shizvizor/nginx-assr -f ./nginx/Dockerfile .
      - name: Push Docker image
        run: docker push shizvizor/nginx-assr:latest
      - name: build-push-postgres
        uses: docker/build-push-action@v4
        with:
          context: ./PostgreSQL/
          push: true
          tags: shizvizor/postgres-assr:latest
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: bake-k8s-files
        uses: azure/k8s-bake@v3
        with:
          renderEngine: 'kompose'
          dockerComposeFile: './docker-compose.yml'
          kompose-version: 'latest'
      - run: kompose convert 
