name: Django CI

on:
  push:
    branches: [ "main", "main-deploy" ]
  pull_request:
    branches: [ "main", "main-deploy" ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: AssrWeb
      run: |
        export DJANGO_DEBUG=1 
        coverage run manage.py collectstatic --noinput --settings=DjangoAssr.settings.testing
        coverage run manage.py makemigrations --settings=DjangoAssr.settings.testing
        coverage run manage.py migrate --settings=DjangoAssr.settings.testing
        coverage run manage.py test --settings=DjangoAssr.settings.testing
        coverage report
        coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: docker
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.docker_login}}
          password: ${{secrets.docker_pass}}
      - name: build-push-backend
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: shizvizor/app-assr:latest
      - name: build-push-nginx
        working-directory: nginx
        run: docker build . -t shizvizor/nginx-assr
      - name: Push Docker image
        run: docker push shizvizor/nginx-assr:latest
      - name: build-push-postgres
        uses: docker/build-push-action@v4
        with:
          context: ./PostgreSQL/
          push: true
          tags: shizvizor/postgres-assr:latest
